/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plataformaapuestas;

/**
 *
 * @author cleme
 */
public class Vista2 extends javax.swing.JFrame {

    /**
     * Creates new form Vista2
     */
    public Vista2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saldoInicialLabel = new javax.swing.JLabel();
        saldoInicialTextField = new javax.swing.JTextField();
        saldoInicialLabel1 = new javax.swing.JLabel();
        probGanarTextField = new javax.swing.JTextField();
        saldoInicialLabel2 = new javax.swing.JLabel();
        saldoInicialLabel3 = new javax.swing.JLabel();
        probGanarTextField1 = new javax.swing.JTextField();
        saldoInicialLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("APUESTA MODO MANUAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        saldoInicialLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saldoInicialLabel.setText("Saldo Inicial: ");
        getContentPane().add(saldoInicialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        getContentPane().add(saldoInicialTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 80, -1));

        saldoInicialLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saldoInicialLabel1.setText("de ganar el juego:");
        getContentPane().add(saldoInicialLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(probGanarTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 80, -1));

        saldoInicialLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saldoInicialLabel2.setText("Probabilidad");
        getContentPane().add(saldoInicialLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        saldoInicialLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saldoInicialLabel3.setText("a apostar:");
        getContentPane().add(saldoInicialLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        getContentPane().add(probGanarTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 80, -1));

        saldoInicialLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saldoInicialLabel4.setText("Dinero ");
        getContentPane().add(saldoInicialLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("%");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("$");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("$");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField probGanarTextField;
    private javax.swing.JTextField probGanarTextField1;
    private javax.swing.JLabel saldoInicialLabel;
    private javax.swing.JLabel saldoInicialLabel1;
    private javax.swing.JLabel saldoInicialLabel2;
    private javax.swing.JLabel saldoInicialLabel3;
    private javax.swing.JLabel saldoInicialLabel4;
    private javax.swing.JTextField saldoInicialTextField;
    // End of variables declaration//GEN-END:variables
}
